name: Build YouTube iPA

on: 
  workflow_dispatch:
    inputs:
      decrypted_youtube_url:
        description: 'Decrypted YouTube URL'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Prepare YouTube iPA
      - name: Prepare YouTube iPA
        id: prepare_youtube
        run: |
          # Extract the file ID from the input URL
          FILE_ID=$(echo "$YOUTUBE_URL" | grep -o 'd/[^/]*' | cut -d'/' -f2)
          echo "Extracted File ID: $FILE_ID"

          OUTPUT_FILE="main/YouTube.ipa"

          # Step 3: Get the confirmation token from Google Drive
          CONFIRM=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate \
            "https://drive.google.com/uc?export=download&id=${FILE_ID}" -O- | grep -o 'confirm=[^&]*' | sed 's/confirm=//')
          echo "Confirmation token: $CONFIRM"

          # Step 4: Download the actual file using the confirmation token
          wget --load-cookies /tmp/cookies.txt \
            "https://drive.google.com/uc?export=download&confirm=${CONFIRM}&id=${FILE_ID}" \
            -O "$OUTPUT_FILE" --no-verbose

          # Step 5: Clean up cookies
          rm -f /tmp/cookies.txt

          # Verify if the file was downloaded successfully
          if [ ! -f "$OUTPUT_FILE" ]; then
            echo "Error: Failed to download YouTube.ipa"
            exit 1
          fi

          # Step 6: Unzip the downloaded file and extract version
          cd ${{ github.workspace }}/main
          mv YouTube.ipa YouTube.zip
          unzip -q YouTube.zip

          youtube_version=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)
          echo "==> YouTube v$youtube_version downloaded!"

          # Step 7: Update the Makefile with the extracted version
          sed -i '' "17s#.*#YOUTUBE_VERSION = ${youtube_version}#g" Makefile
          echo "youtube_version=${youtube_version}" >> $GITHUB_OUTPUT
        env:
          YOUTUBE_URL: ${{ github.event.inputs.decrypted_youtube_url }}
