name: Build YouTube iPA

on: 
  workflow_dispatch:
    inputs:
      release_download_url:
        description: 'GitHub Release Download URL'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Download YouTube iPA from GitHub Releases
      - name: Download YouTube iPA
        run: |
          DOWNLOAD_URL="${{ github.event.inputs.release_download_url }}"
          echo "Downloading from: $DOWNLOAD_URL"
          
          # Use curl with -L to follow redirects and -H for GitHub headers
          mkdir -p main
          curl -L -H "Accept: application/octet-stream" "$DOWNLOAD_URL" -o main/YouTube.ipa

          # Verify if the file was downloaded successfully
          if [ ! -f "main/YouTube.ipa" ]; then
            echo "Error: Failed to download YouTube.ipa"
            exit 1
          fi

          echo "File downloaded successfully: main/YouTube.ipa"

      # Step 3: Unzip the downloaded file and extract version
      - name: Extract and Process YouTube iPA
        run: |
          cd main
          mv YouTube.ipa YouTube.zip
          unzip -q YouTube.zip

          youtube_version=$(defaults read "$(pwd)/Payload/YouTube.app/Info" CFBundleVersion)
          echo "==> YouTube v$youtube_version downloaded!"

          # Update the Makefile with the extracted version
          sed -i '' "17s#.*#YOUTUBE_VERSION = ${youtube_version}#g" Makefile
          echo "youtube_version=${youtube_version}" >> $GITHUB_OUTPUT
